// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: quant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuantService_Ping_FullMethodName        = "/quant.v1.QuantService/Ping"
	QuantService_RunBacktest_FullMethodName = "/quant.v1.QuantService/RunBacktest"
)

// QuantServiceClient is the client API for QuantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QuantService 是 Python 回测服务对外暴露的 gRPC 接口。
// Go 主服务作为客户端调用；当前 M0 阶段仅打通骨架。
type QuantServiceClient interface {
	// Ping 健康检查，验证 Go <-> Python gRPC 链路连通。
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// RunBacktest 运行一次回测：Go 传入历史 K 线 + 策略参数，
	// Python 用 backtrader 跑完返回绩效与净值曲线。
	// M0 阶段为占位实现，返回桩数据。
	RunBacktest(ctx context.Context, in *BacktestRequest, opts ...grpc.CallOption) (*BacktestResponse, error)
}

type quantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantServiceClient(cc grpc.ClientConnInterface) QuantServiceClient {
	return &quantServiceClient{cc}
}

func (c *quantServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, QuantService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantServiceClient) RunBacktest(ctx context.Context, in *BacktestRequest, opts ...grpc.CallOption) (*BacktestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BacktestResponse)
	err := c.cc.Invoke(ctx, QuantService_RunBacktest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantServiceServer is the server API for QuantService service.
// All implementations must embed UnimplementedQuantServiceServer
// for forward compatibility.
//
// QuantService 是 Python 回测服务对外暴露的 gRPC 接口。
// Go 主服务作为客户端调用；当前 M0 阶段仅打通骨架。
type QuantServiceServer interface {
	// Ping 健康检查，验证 Go <-> Python gRPC 链路连通。
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// RunBacktest 运行一次回测：Go 传入历史 K 线 + 策略参数，
	// Python 用 backtrader 跑完返回绩效与净值曲线。
	// M0 阶段为占位实现，返回桩数据。
	RunBacktest(context.Context, *BacktestRequest) (*BacktestResponse, error)
	mustEmbedUnimplementedQuantServiceServer()
}

// UnimplementedQuantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuantServiceServer struct{}

func (UnimplementedQuantServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedQuantServiceServer) RunBacktest(context.Context, *BacktestRequest) (*BacktestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunBacktest not implemented")
}
func (UnimplementedQuantServiceServer) mustEmbedUnimplementedQuantServiceServer() {}
func (UnimplementedQuantServiceServer) testEmbeddedByValue()                      {}

// UnsafeQuantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantServiceServer will
// result in compilation errors.
type UnsafeQuantServiceServer interface {
	mustEmbedUnimplementedQuantServiceServer()
}

func RegisterQuantServiceServer(s grpc.ServiceRegistrar, srv QuantServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuantService_ServiceDesc, srv)
}

func _QuantService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantService_RunBacktest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BacktestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantServiceServer).RunBacktest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuantService_RunBacktest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantServiceServer).RunBacktest(ctx, req.(*BacktestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuantService_ServiceDesc is the grpc.ServiceDesc for QuantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quant.v1.QuantService",
	HandlerType: (*QuantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _QuantService_Ping_Handler,
		},
		{
			MethodName: "RunBacktest",
			Handler:    _QuantService_RunBacktest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quant.proto",
}
