// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: quant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_quant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // 回应方服务名，便于确认是 Python 端
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_quant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// 单根 K 线（OHLCV）。时间用 Unix 毫秒时间戳（UTC）。
type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenTime      int64                  `protobuf:"varint,1,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_quant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{2}
}

func (x *Kline) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *Kline) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Kline) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Kline) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Kline) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Kline) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type BacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                                           // 如 CRYPTO.BTC-USDT
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`                                                                       // 策略名，如 "dual_ma"
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 策略参数（字符串键值，Python 端解析）
	InitialCash   float64                `protobuf:"fixed64,4,opt,name=initial_cash,json=initialCash,proto3" json:"initial_cash,omitempty"`                                            // 初始资金
	Commission    float64                `protobuf:"fixed64,5,opt,name=commission,proto3" json:"commission,omitempty"`                                                                 // 手续费率
	Klines        []*Kline               `protobuf:"bytes,6,rep,name=klines,proto3" json:"klines,omitempty"`                                                                           // 历史 K 线序列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestRequest) Reset() {
	*x = BacktestRequest{}
	mi := &file_quant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestRequest) ProtoMessage() {}

func (x *BacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestRequest.ProtoReflect.Descriptor instead.
func (*BacktestRequest) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{3}
}

func (x *BacktestRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BacktestRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *BacktestRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BacktestRequest) GetInitialCash() float64 {
	if x != nil {
		return x.InitialCash
	}
	return 0
}

func (x *BacktestRequest) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *BacktestRequest) GetKlines() []*Kline {
	if x != nil {
		return x.Klines
	}
	return nil
}

// 回测绩效指标。
type BacktestMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalReturn   float64                `protobuf:"fixed64,1,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"`    // 总收益率
	AnnualReturn  float64                `protobuf:"fixed64,2,opt,name=annual_return,json=annualReturn,proto3" json:"annual_return,omitempty"` // 年化收益率
	MaxDrawdown   float64                `protobuf:"fixed64,3,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`    // 最大回撤
	Sharpe        float64                `protobuf:"fixed64,4,opt,name=sharpe,proto3" json:"sharpe,omitempty"`                                 // 夏普比率
	TradeCount    int64                  `protobuf:"varint,5,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`        // 成交次数
	WinRate       float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`                // 胜率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestMetrics) Reset() {
	*x = BacktestMetrics{}
	mi := &file_quant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestMetrics) ProtoMessage() {}

func (x *BacktestMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestMetrics.ProtoReflect.Descriptor instead.
func (*BacktestMetrics) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{4}
}

func (x *BacktestMetrics) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *BacktestMetrics) GetAnnualReturn() float64 {
	if x != nil {
		return x.AnnualReturn
	}
	return 0
}

func (x *BacktestMetrics) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *BacktestMetrics) GetSharpe() float64 {
	if x != nil {
		return x.Sharpe
	}
	return 0
}

func (x *BacktestMetrics) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *BacktestMetrics) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

// 净值曲线上的一个点。
type EquityPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquityPoint) Reset() {
	*x = EquityPoint{}
	mi := &file_quant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquityPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquityPoint) ProtoMessage() {}

func (x *EquityPoint) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquityPoint.ProtoReflect.Descriptor instead.
func (*EquityPoint) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{5}
}

func (x *EquityPoint) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *EquityPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 一笔成交（用于在 K 线图上标买卖点）。
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`          // Unix 毫秒（与 Kline.open_time 同口径）
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`           // "buy" / "sell"
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`       // 成交价
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // 成交数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_quant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{6}
}

func (x *Trade) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Trade) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *BacktestMetrics       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	EquityCurve   []*EquityPoint         `protobuf:"bytes,2,rep,name=equity_curve,json=equityCurve,proto3" json:"equity_curve,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,3,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestResponse) Reset() {
	*x = BacktestResponse{}
	mi := &file_quant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestResponse) ProtoMessage() {}

func (x *BacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestResponse.ProtoReflect.Descriptor instead.
func (*BacktestResponse) Descriptor() ([]byte, []int) {
	return file_quant_proto_rawDescGZIP(), []int{7}
}

func (x *BacktestResponse) GetMetrics() *BacktestMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *BacktestResponse) GetEquityCurve() []*EquityPoint {
	if x != nil {
		return x.EquityCurve
	}
	return nil
}

func (x *BacktestResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_quant_proto protoreflect.FileDescriptor

const file_quant_proto_rawDesc = "" +
	"\n" +
	"\vquant.proto\x12\bquant.v1\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"B\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\"\x8c\x01\n" +
	"\x05Kline\x12\x1b\n" +
	"\topen_time\x18\x01 \x01(\x03R\bopenTime\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\xab\x02\n" +
	"\x0fBacktestRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12=\n" +
	"\x06params\x18\x03 \x03(\v2%.quant.v1.BacktestRequest.ParamsEntryR\x06params\x12!\n" +
	"\finitial_cash\x18\x04 \x01(\x01R\vinitialCash\x12\x1e\n" +
	"\n" +
	"commission\x18\x05 \x01(\x01R\n" +
	"commission\x12'\n" +
	"\x06klines\x18\x06 \x03(\v2\x0f.quant.v1.KlineR\x06klines\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x0fBacktestMetrics\x12!\n" +
	"\ftotal_return\x18\x01 \x01(\x01R\vtotalReturn\x12#\n" +
	"\rannual_return\x18\x02 \x01(\x01R\fannualReturn\x12!\n" +
	"\fmax_drawdown\x18\x03 \x01(\x01R\vmaxDrawdown\x12\x16\n" +
	"\x06sharpe\x18\x04 \x01(\x01R\x06sharpe\x12\x1f\n" +
	"\vtrade_count\x18\x05 \x01(\x03R\n" +
	"tradeCount\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\"7\n" +
	"\vEquityPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"a\n" +
	"\x05Trade\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\"\xaa\x01\n" +
	"\x10BacktestResponse\x123\n" +
	"\ametrics\x18\x01 \x01(\v2\x19.quant.v1.BacktestMetricsR\ametrics\x128\n" +
	"\fequity_curve\x18\x02 \x03(\v2\x15.quant.v1.EquityPointR\vequityCurve\x12'\n" +
	"\x06trades\x18\x03 \x03(\v2\x0f.quant.v1.TradeR\x06trades2\x8b\x01\n" +
	"\fQuantService\x125\n" +
	"\x04Ping\x12\x15.quant.v1.PingRequest\x1a\x16.quant.v1.PingResponse\x12D\n" +
	"\vRunBacktest\x12\x19.quant.v1.BacktestRequest\x1a\x1a.quant.v1.BacktestResponseB4Z2github.com/jiangbohhh/candleforge/backend-go/pb;pbb\x06proto3"

var (
	file_quant_proto_rawDescOnce sync.Once
	file_quant_proto_rawDescData []byte
)

func file_quant_proto_rawDescGZIP() []byte {
	file_quant_proto_rawDescOnce.Do(func() {
		file_quant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quant_proto_rawDesc), len(file_quant_proto_rawDesc)))
	})
	return file_quant_proto_rawDescData
}

var file_quant_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_quant_proto_goTypes = []any{
	(*PingRequest)(nil),      // 0: quant.v1.PingRequest
	(*PingResponse)(nil),     // 1: quant.v1.PingResponse
	(*Kline)(nil),            // 2: quant.v1.Kline
	(*BacktestRequest)(nil),  // 3: quant.v1.BacktestRequest
	(*BacktestMetrics)(nil),  // 4: quant.v1.BacktestMetrics
	(*EquityPoint)(nil),      // 5: quant.v1.EquityPoint
	(*Trade)(nil),            // 6: quant.v1.Trade
	(*BacktestResponse)(nil), // 7: quant.v1.BacktestResponse
	nil,                      // 8: quant.v1.BacktestRequest.ParamsEntry
}
var file_quant_proto_depIdxs = []int32{
	8, // 0: quant.v1.BacktestRequest.params:type_name -> quant.v1.BacktestRequest.ParamsEntry
	2, // 1: quant.v1.BacktestRequest.klines:type_name -> quant.v1.Kline
	4, // 2: quant.v1.BacktestResponse.metrics:type_name -> quant.v1.BacktestMetrics
	5, // 3: quant.v1.BacktestResponse.equity_curve:type_name -> quant.v1.EquityPoint
	6, // 4: quant.v1.BacktestResponse.trades:type_name -> quant.v1.Trade
	0, // 5: quant.v1.QuantService.Ping:input_type -> quant.v1.PingRequest
	3, // 6: quant.v1.QuantService.RunBacktest:input_type -> quant.v1.BacktestRequest
	1, // 7: quant.v1.QuantService.Ping:output_type -> quant.v1.PingResponse
	7, // 8: quant.v1.QuantService.RunBacktest:output_type -> quant.v1.BacktestResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_quant_proto_init() }
func file_quant_proto_init() {
	if File_quant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quant_proto_rawDesc), len(file_quant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quant_proto_goTypes,
		DependencyIndexes: file_quant_proto_depIdxs,
		MessageInfos:      file_quant_proto_msgTypes,
	}.Build()
	File_quant_proto = out.File
	file_quant_proto_goTypes = nil
	file_quant_proto_depIdxs = nil
}
