# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quant.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'quant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquant.proto\x12\x08quant.v1\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"b\n\x05Kline\x12\x11\n\topen_time\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"\xe4\x01\n\x0f\x42\x61\x63ktestRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x01(\t\x12\x35\n\x06params\x18\x03 \x03(\x0b\x32%.quant.v1.BacktestRequest.ParamsEntry\x12\x14\n\x0cinitial_cash\x18\x04 \x01(\x01\x12\x12\n\ncommission\x18\x05 \x01(\x01\x12\x1f\n\x06klines\x18\x06 \x03(\x0b\x32\x0f.quant.v1.Kline\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8b\x01\n\x0f\x42\x61\x63ktestMetrics\x12\x14\n\x0ctotal_return\x18\x01 \x01(\x01\x12\x15\n\rannual_return\x18\x02 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x03 \x01(\x01\x12\x0e\n\x06sharpe\x18\x04 \x01(\x01\x12\x13\n\x0btrade_count\x18\x05 \x01(\x03\x12\x10\n\x08win_rate\x18\x06 \x01(\x01\"*\n\x0b\x45quityPoint\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\"k\n\x10\x42\x61\x63ktestResponse\x12*\n\x07metrics\x18\x01 \x01(\x0b\x32\x19.quant.v1.BacktestMetrics\x12+\n\x0c\x65quity_curve\x18\x02 \x03(\x0b\x32\x15.quant.v1.EquityPoint2\x8b\x01\n\x0cQuantService\x12\x35\n\x04Ping\x12\x15.quant.v1.PingRequest\x1a\x16.quant.v1.PingResponse\x12\x44\n\x0bRunBacktest\x12\x19.quant.v1.BacktestRequest\x1a\x1a.quant.v1.BacktestResponseB4Z2github.com/jiangbohhh/candleforge/backend-go/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/jiangbohhh/candleforge/backend-go/pb;pb'
  _globals['_BACKTESTREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_BACKTESTREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_PINGREQUEST']._serialized_start=25
  _globals['_PINGREQUEST']._serialized_end=55
  _globals['_PINGRESPONSE']._serialized_start=57
  _globals['_PINGRESPONSE']._serialized_end=105
  _globals['_KLINE']._serialized_start=107
  _globals['_KLINE']._serialized_end=205
  _globals['_BACKTESTREQUEST']._serialized_start=208
  _globals['_BACKTESTREQUEST']._serialized_end=436
  _globals['_BACKTESTREQUEST_PARAMSENTRY']._serialized_start=391
  _globals['_BACKTESTREQUEST_PARAMSENTRY']._serialized_end=436
  _globals['_BACKTESTMETRICS']._serialized_start=439
  _globals['_BACKTESTMETRICS']._serialized_end=578
  _globals['_EQUITYPOINT']._serialized_start=580
  _globals['_EQUITYPOINT']._serialized_end=622
  _globals['_BACKTESTRESPONSE']._serialized_start=624
  _globals['_BACKTESTRESPONSE']._serialized_end=731
  _globals['_QUANTSERVICE']._serialized_start=734
  _globals['_QUANTSERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
