# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import quant_pb2 as quant__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantServiceStub:
    """QuantService 是 Python 回测服务对外暴露的 gRPC 接口。
    Go 主服务作为客户端调用；当前 M0 阶段仅打通骨架。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/quant.v1.QuantService/Ping',
                request_serializer=quant__pb2.PingRequest.SerializeToString,
                response_deserializer=quant__pb2.PingResponse.FromString,
                _registered_method=True)
        self.RunBacktest = channel.unary_unary(
                '/quant.v1.QuantService/RunBacktest',
                request_serializer=quant__pb2.BacktestRequest.SerializeToString,
                response_deserializer=quant__pb2.BacktestResponse.FromString,
                _registered_method=True)


class QuantServiceServicer:
    """QuantService 是 Python 回测服务对外暴露的 gRPC 接口。
    Go 主服务作为客户端调用；当前 M0 阶段仅打通骨架。
    """

    def Ping(self, request, context):
        """Ping 健康检查，验证 Go <-> Python gRPC 链路连通。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBacktest(self, request, context):
        """RunBacktest 运行一次回测：Go 传入历史 K 线 + 策略参数，
        Python 用 backtrader 跑完返回绩效与净值曲线。
        M0 阶段为占位实现，返回桩数据。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=quant__pb2.PingRequest.FromString,
                    response_serializer=quant__pb2.PingResponse.SerializeToString,
            ),
            'RunBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=quant__pb2.BacktestRequest.FromString,
                    response_serializer=quant__pb2.BacktestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.QuantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.QuantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantService:
    """QuantService 是 Python 回测服务对外暴露的 gRPC 接口。
    Go 主服务作为客户端调用；当前 M0 阶段仅打通骨架。
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.QuantService/Ping',
            quant__pb2.PingRequest.SerializeToString,
            quant__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.QuantService/RunBacktest',
            quant__pb2.BacktestRequest.SerializeToString,
            quant__pb2.BacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
